#!/bin/bash

PATH_BAK=$PATH
export PATH=$PATH:/home/jaideep/anaconda2/bin
. activate tensorflow
python nn_const_data_fire_v5_pureNN.py
. deactivate
sed -i -e "s/\\[/ /g" ../output_ssaplus_pureNN/weights_ba.txt
sed -i -e "s/\\]/ /g" ../output_ssaplus_pureNN/weights_ba.txt
sed -i -e "s/\\,/ /g" ../output_ssaplus_pureNN/weights_ba.txt
PATH=$PATH_BAK

